import type { ApiFailure, ApiSuccess } from '../../../../../shared/types/api'
import { getServerApplicantRosterService, RosterDatabaseValidationError } from '../../../../modules/admin/applicant-roster'
import { requireRecentAdminContext } from '../../../../utils/admin-context'
import { AppError, toApiFailure } from '../../../../utils/app-error'
import { readBoundedRequestBody, RequestBodyLimitError, RESOURCE_IMPORT_MAX_REQUEST_BODY_BYTES } from '../../../../utils/bounded-request-body'
type Service = ReturnType<typeof getServerApplicantRosterService>
type Dependencies = { roster: Pick<Service, 'apply'>, getRequestId: (event: unknown) => string, readRawBody: (event: unknown) => Promise<string | undefined>, setHeader: (event: unknown, name: string, value: string) => void, setStatus: (event: unknown, status: number) => void, requireRecentAdmin: (event: unknown) => { userId: string } }
export const createRosterApplyHandler = (dependencies: Dependencies) => async (event: unknown): Promise<ApiSuccess<Awaited<ReturnType<Service['apply']>>> | ApiFailure> => { const requestId = dependencies.getRequestId(event); dependencies.setHeader(event, 'cache-control', 'private, no-store'); dependencies.setHeader(event, 'content-type', 'application/json; charset=utf-8'); try { const admin = dependencies.requireRecentAdmin(event); return { data: await dependencies.roster.apply(JSON.parse(await dependencies.readRawBody(event) ?? ''), { adminUserId: admin.userId, requestId }), requestId }; } catch (error) { if (error instanceof RosterDatabaseValidationError) dependencies.setHeader(event, 'x-roster-diagnostic', error.diagnosticCode); const publicError = error instanceof AppError ? error : error instanceof RequestBodyLimitError || error instanceof SyntaxError ? new AppError('ROSTER_INVALID') : new AppError('INTERNAL_ERROR'); dependencies.setStatus(event, publicError.statusCode); return toApiFailure(publicError, requestId) } }
export default defineEventHandler(event => createRosterApplyHandler({ roster: getServerApplicantRosterService(), getRequestId: requestEvent => typeof (requestEvent as { context?: { requestId?: unknown } }).context?.requestId === 'string' ? (requestEvent as { context: { requestId: string } }).context.requestId : crypto.randomUUID(), readRawBody: requestEvent => readBoundedRequestBody(requestEvent, RESOURCE_IMPORT_MAX_REQUEST_BODY_BYTES), requireRecentAdmin: requestEvent => requireRecentAdminContext(requestEvent, 15), setHeader: (event, name, value) => setResponseHeader(event as never, name, value), setStatus: (event, status) => setResponseStatus(event as never, status) })(event))
